// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoPlace() {
  return window['go']['main']['App']['AutoPlace']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HostLanGame() {
  return window['go']['main']['App']['HostLanGame']();
}

export function JoinLanGame(arg1) {
  return window['go']['main']['App']['JoinLanGame'](arg1);
}

export function LanAutoPlace() {
  return window['go']['main']['App']['LanAutoPlace']();
}

export function LanFire(arg1, arg2) {
  return window['go']['main']['App']['LanFire'](arg1, arg2);
}

export function LanGetState() {
  return window['go']['main']['App']['LanGetState']();
}

export function LanPlaceShip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LanPlaceShip'](arg1, arg2, arg3, arg4);
}

export function LanReady() {
  return window['go']['main']['App']['LanReady']();
}

export function LanRemoveShip(arg1) {
  return window['go']['main']['App']['LanRemoveShip'](arg1);
}

export function LanSendChat(arg1) {
  return window['go']['main']['App']['LanSendChat'](arg1);
}

export function NewGame(arg1) {
  return window['go']['main']['App']['NewGame'](arg1);
}

export function PlaceShip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlaceShip'](arg1, arg2, arg3, arg4);
}

export function PlayerFire(arg1, arg2) {
  return window['go']['main']['App']['PlayerFire'](arg1, arg2);
}

export function RemoveShip(arg1) {
  return window['go']['main']['App']['RemoveShip'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function StartBattle() {
  return window['go']['main']['App']['StartBattle']();
}
