// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';

export function AutoPlace():Promise<game.SessionState>;

export function GetState():Promise<game.SessionState>;

export function HostLanGame():Promise<string>;

export function JoinLanGame(arg1:string):Promise<game.SessionState>;

export function LanAutoPlace():Promise<game.SessionState>;

export function LanFire(arg1:number,arg2:number):Promise<game.SessionState>;

export function LanGetState():Promise<game.SessionState>;

export function LanPlaceShip(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<game.SessionState>;

export function LanReady():Promise<game.SessionState>;

export function LanRemoveShip(arg1:number):Promise<game.SessionState>;

export function LanSendChat(arg1:string):Promise<void>;

export function NewGame(arg1:number):Promise<game.SessionState>;

export function PlaceShip(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<game.SessionState>;

export function PlayerFire(arg1:number,arg2:number):Promise<game.SessionState>;

export function RemoveShip(arg1:number):Promise<game.SessionState>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function StartBattle():Promise<game.SessionState>;
